let fullStackKeys = [
    "full stack",
    "full-stack",
    "web dev",
    "react",
    "mongodb",
    "jenkins",
    "html",
    "css",
    "javascript",
    "express",
    "node",
    "nodejs",
    "node js",
    "typescript",
    "java",
    "spring",
    "spring boot",
    "REST",
    "REST API",
    "frontend",
    "backend",
    "c++",
    "python",
    "tdd",
    "test driven",
    "test-driven-development",
    "agile",
    "scrum",
    "unit",
    "integration",
    "cloud",
    "google cloud platform",
    "gcp",
    "AWS",
    "amazon web services",
    "github",
    "git",
    "UML",
    "mobile",
    "mobile dev",
    "dart",
    "flutter",
    "react native",
    "react-native",
];

module.exports = { fullStackKeys };